### ISSUE TITLE
Inconsistently sorted coordinate points for certain words in kant_aufklaerung sample

### ISSUE THREAD

**Issue by kba** [OCR-D/assets#11]
E.g. all `Word` with `ID` `word_*` in https://github.com/OCR-D/assets/blob/master/data/kant_aufklaerung_1784/page/kant_aufklaerung_1784_0020.xml, such as https://github.com/OCR-D/assets/blob/master/data/kant_aufklaerung_1784/page/kant_aufklaerung_1784_0020.xml#L71

Everywhere else, coordinates are sorted clock-wise starting with top-left but these coordinates start with bottom-right.

Can this be fixed upstream? If not, we could adapt the coordinate translation utilities in core.

@tboenig @bertsky

**Comment by finkf** [comment]
One more thing: are there really 4 Points needed? If we use rectangles top-left and bottom-right would be sufficient.

**Comment by kba** [comment]
I interpret `page:Coords` to be a points of a polygon, not necessarily a rectangle. c.f. https://github.com/PRImA-Research-Lab/PAGE-XML/blob/master/pagecontent/schema/pagecontent.xsd#L441

A two-coordinate tuple could be a special case but translating between all these representations is confusing enough as it is IMHO.

**Comment by finkf** [comment]
Yes OK.
But then I would suggest not to rely on any ordering of the points. If you have more than 4 points or less than 4 (technically a triangle is a polygon, too) You need a more robust way to calculate the according bounding boxes anyway.

**Comment by finkf** [comment]
And you cannot check/enforce the ordering in a schema AFAIK.

**Comment by kba** [comment]
The problem behind this issue was a segfault in tesseract for certain words IIRC.

I wouldn't want to enforce this via schema, I was just curious how this happens since the coordinates are shifted.

Good point about polygons and bounding boxes, so far we do not have support for bounding polygons with boxes at all because we assume coordinates to be coordinates.

@cneud @wrznr @tboenig Do we have samples of non-rectangular text blocks to test?

**Comment by bertsky** [comment]
This point is probably decisive. Even if we would now fix this upstream, we can never be sure how components evolve. Since we have no (simple and expectable) way to check whether the _clock-wise-tl-starting_ assumption is fulfilled, some day things **will** go wrong. 

That goes for weaker assumptions too: We cannot enforce clock-wise or even ordered path for points via XML schema.

So how much more expensive would a robust solution in utils.py be? Every PAGE element has coordinates, every page goes through several processing steps involving core's functions.

**Comment by cneud** [comment]
@kba Yes, we have plenty examples (incl. some with PAGE ground truth) of non-rectangular text blocks, will try to upload some samples over the next few days.

**Comment by kba** [comment]
> So how much more expensive would a robust solution in utils.py be?

Not that much I guess. I'll send a PR.

**Comment by kba** [comment]
> I do have a simple fix for this -- if you are interested in it.

Didn't see this before. Contributions welcome :)

**Comment by finkf** [comment]
[pull request](https://github.com/OCR-D/core/pull/159)
