### ISSUE TITLE
https://github.com/OCR-D/assets/blob/master/data/kant_aufklaerung_1784-binarized/mets.xml does not conform to specification

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/assets#14]
Quote: If used, the GROUPID of the page MUST BE the ID of the file that represents the original image. In other words: For the file representing the original image, ID and GROUPID must be identical.

**Comment by kba** [comment]
Feel free to fix, it's probably in the other variants as well.

Reminds me I wanted to fix workspace validation...
