### ISSUE TITLE
The asset SBB0000F29300010000 is missing files.

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/assets#22]
Something's gone wrong. Only 7 files of 28 referenced in METS are still there.
Also the paths for the existing ones are not valid.

**Comment by kba** [comment]
It is referencing imaginary files, true. Consider it a network resilience test :-)

Only the bundled files (with relative file paths) can be used.

**Comment by VolkerHartmann** [comment]
It should then also be marked as invalid!? Validating it with 'ocrd workspace validate' will fail.

**Comment by kba** [comment]
Good point, I'll set up CI for workspace validation of all data folders.

**Comment by kba** [comment]
Done [![CircleCI](https://circleci.com/gh/OCR-D/assets.svg?style=svg)](https://circleci.com/gh/OCR-D/assets)

By default the validation won't download images now, can be enabled with `--download` to `ocrd workspace validate`.
