### ISSUE TITLE
Invalid xml file in dorn_uppedat_1507.zip 

### ISSUE THREAD

**Issue by finkf** [OCR-D/assets#23]
The file `page/dorn_uppedat_1507_00004.xml` in the ground-truth zip file is invalid.
It is just a missing `<` in the metadata at `Creator`:
```xml
<Metadata>
        <Creator>OCR-D/Creator>
        <Created>2016-12-07T15:18:07.272+01:00</Created>
        <LastChange>2017-03-07T18:04:10.221+01:00</LastChange>
      
    </Metadata>
```

**Comment by ehrmn** [comment]
Thanks for the note. Just uploaded a corrected version.
