### ISSUE TITLE
multiple issues in kant_aufklaerung_1784-page-block-line-word_glyph

### ISSUE THREAD

**Issue by bertsky** [OCR-D/assets#26]
1. there are filegroups referencing invalid URLs:
```sh
ocrd workspace clone -a data/kant_aufklaerung_1784-page-block-line-word_glyph/data/mets.xml
Exception: Not found: https://github.com/OCR-D/assets/raw/master/data/kant_aufklaerung_1784/OCR-D-GT-PAGE/PAGE_0017_PAGE (HTTP 404)
```
(it seems that `data/` is missing in the path)

2. the two filegroups `OCR-D-GT-SEG-WORD` and `OCR-D-GT-SEG-WORD-GLYPH` use the same directory and files

3. glyph coordinates are not rectangles or rough polygons but detailed envelope paths like `135,374 135,375 137,375 137,376 156,376 156,377 158,377 158,378 159,378 159,379 160,379 160,380 161,380 161,381 162,381 162,386 164,386 164,398 165,398 165,400 166,400 166,401 167,401 167,404 168,404 168,410 167,410 167,414 166,414 166,415 165,415 165,417 164,417 164,419 163,419 163,420 162,420 162,421 161,421 161,422 160,422 160,423 159,423 159,424 157,424 157,425 155,425 155,426 154,426 154,427 151,427 151,428 147,428 147,429 142,429 142,430 139,430 139,429 137,429 137,428 135,428 135,427 134,427 134,426 116,426 116,425 115,425 115,420 114,420 115,420 115,404 116,404 116,382 117,382 117,379 118,379 118,378 120,378 120,377 121,377 121,376 123,376 123,375 124,375 124,374` – is this correct? (I am asking because I am still considering using coordinates for alignment, which would become impractical with such data.)

4. non-standard or non-normalised characters like `` U+F502 (from private use area, instead of letter `c`) or `` U+E644 (also private use area, instead of letter `ö` or combination `oͤ`

5. the `README.md` still mentions the deleted `page-with-glyphs.xml` but not the new file

**Comment by tboenig** [comment]
@bertsky thanks for debugging.
1. The METS problem should be fixed.
2. That's right. There is no separate example for recording WORD in Page.
3. It's correct, all possibilities can occur. I'm sorry, glyphs only with coordinates based on squares do not represented reality.
4. All Unicode that refer to private areas should now be returned to "Standard" Unicode. In the case of ligatures there are now sometimes two characters (e.g. the ligature ch).
But see: https://ocr-d.github.io/gt//trans_documentation/ocr_d_koordinationsgremium_codierung.html
5. Readme.md added and corrected.

**Comment by bertsky** [comment]
Thanks @tboenig – that was fast!

Regarding 4, now I am puzzled: I still find `ﬅ` U+FB05 (`ſt` ligature from Unicode-Ll) in the new version. It does appear in the IMPACT table you referenced, but how is that relevant here? As far as I understand, our GT guidelines are different: ligatures are to be split up in all but transcription level 3 – but all the other GT files seem to be level 2. Which one is correct?

BTW, the [table on ligatures](https://ocr-d.github.io/gt//trans_documentation/trLigaturen2.html) in your guidelines has a typo: for the `ſt` ligature it says `U+EADA` instead of `U+FB05`.

**Comment by tboenig** [comment]
@bertsky Thanks,

- the  [table on ligatures](https://ocr-d.github.io/gt//trans_documentation/trLigaturen2.html) 
The error in the table is corrected.
- thank you again, for your reading carefully:
The current version has to be corrected again, it would correspond to a Level 3 version then, I'm working on a correct version for Level 2 right now. This version will also be published.
