### ISSUE TITLE
missing words in GT

### ISSUE THREAD

**Issue by bertsky** [OCR-D/assets#31]
Probably just a singular error:

In [weigel_gnothi02_1618](https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/3f0e9bcf-c1a7-479d-b8dc-ddfb262d2738/data/weigel_gnothi02_1618.ocrd.zip), on page `phys_0001` region `TextRegion_1488379719413_342` line `tl_7`, the first 3 words ("auf den Erſten") are missing from the annotation (both as `Word` elements and in the `TextEquiv` of the `TextLine`).

**Comment by tboenig** [comment]
Ok, we see the problem and we will fixed.

**Comment by tboenig** [comment]
@kba Why did the consistency check of the workspace validation not raise an issue for this?

**Comment by bertsky** [comment]
@tboenig It cannot, because the PAGE annotation is self-consistent – it is simply not accurate (w.r.t. to the image), because those words are missing on all levels.

**Comment by kba** [comment]
OK, now I get it. If it's consistently wrong on all levels, there's nothing to check here.

**Comment by bertsky** [comment]
@EEngl52 closing because this is solved upstream now? I cannot see a new release on https://ocr-d-repo.scc.kit.edu/api/v1/metastore/bagit yet – is it somewhere else?

**Comment by bertsky** [comment]
@EEngl52, I received an email from @tboenig with a prerelease which shows this is fixed upstream – thanks!
