### ISSUE TITLE
Border instead of PrintSpace in GT

### ISSUE THREAD

**Issue by bertsky** [OCR-D/assets#34]
The current GT bags in [the repo](https://ocr-d-repo.scc.kit.edu/api/v1/metastore/bagit) all use `PrintSpace` to annotate page-level cropping (including marginals and page numbers). But according to the PAGE standard `Border` should be used for that.

Please re-export, so PAGE tools dealing with coordinates do not have to be stretched to expect this transgression.

**Comment by kba** [comment]
We will adapt the GT, as automatically as possible.

Also need to define the mechanism in the spec.

**Comment by tboenig** [comment]
We will replace ``printspace`` with ``boder`` and in the spec (https://ocr-d.github.io/gt//trans_documentation/lySatzspiegel.html) we add information for using ``border``.

**Comment by bertsky** [comment]
Not solved here yet:
https://github.com/OCR-D/assets/blob/c1a598d7c23ded500cc01d3fbf3ecc7e00afa805/data/kant_aufklaerung_1784-binarized/data/OCR-D-GT-WORD/INPUT_0017.xml#L19-L21

**Comment by bertsky** [comment]
Also:

https://github.com/OCR-D/assets/blob/c1a598d7c23ded500cc01d3fbf3ecc7e00afa805/data/kant_aufklaerung_1784-binarized/data/OCR-D-GT-WORD/INPUT_0020.xml#L21-L23

https://github.com/OCR-D/assets/blob/c1a598d7c23ded500cc01d3fbf3ecc7e00afa805/data/kant_aufklaerung_1784-jp2/data/OCR-D-GT-PAGE/PAGE_0020_PAGE.xml#L14-L16

https://github.com/OCR-D/assets/blob/c1a598d7c23ded500cc01d3fbf3ecc7e00afa805/data/kant_aufklaerung_1784/data/OCR-D-GT-PAGE/PAGE_0017_PAGE.xml#L13-L15

https://github.com/OCR-D/assets/blob/c1a598d7c23ded500cc01d3fbf3ecc7e00afa805/data/kant_aufklaerung_1784/data/OCR-D-GT-PAGE/PAGE_0020_PAGE.xml#L14-L16

@tboenig @kba please fix or (at least re-open)!
