### ISSUE TITLE
1000pages: Graphic overlapped by text region in page 14 of "fischer_werkzeugmachinen01_1900"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#42]
The text-wrapped figure on page 14 of `fischer_werkzeugmachinen01_1900` is completely covered by a large text region.

**Comment by tboenig** [comment]
with next version of corpus 1000pages the bug is fixed

**Comment by tboenig** [comment]
The bug is fixed. You find the new version in the raw directory and a new mets file (mets_new.xml).

**Comment by wrznr** [comment]
Where can I find `mets_new.xml`?

**Comment by kba** [comment]
@wrznr Can you verify this was fixed in https://ocr-d-repo.scc.kit.edu/api/v1/metastore/bagit/ocrdidentifier?ocrdidentifier=ocrd_data_structur_fischer_werkzeugmaschinen01_1900 ?

**Comment by wrznr** [comment]
http://odo.dwds.de/~kmw/raw_fischer_werkzeugmaschinen01_1900_OCR-D-IMG-CROP_0014.dbg.png
