### ISSUE TITLE
1000pages: Paragraph missing on page 0013 of "rein_japan02_1886"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#44]
A whole paragraph is not present as `TextRegion` on page 0013 of `rein_japan02_1886`.
![rein_japan02_1886_OCR-D-IMG-CROP_0013 dbg](https://user-images.githubusercontent.com/26707219/64758296-881b0a80-d534-11e9-92a7-60bf73c22a39.png)
![rein_japan02_1886_OCR-D-IMG-CROP_0013](https://user-images.githubusercontent.com/26707219/64758297-881b0a80-d534-11e9-9ad1-910d6da84fba.png)

**Comment by tboenig** [comment]
fixed, see raw directory

**Comment by tboenig** [comment]
fixed
