### ISSUE TITLE
1000pages: Graphic embedded in text region on page 0009 of "fischer_werkzeugmachinen01_1900""

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#46]
The graphic is clearly not embedded (two different paragraphs, cf. for a correct annotation page 0010 in the same volume).
![fischer_werkzeugmaschinen01_1900_OCR-D-IMG-CROP_0009 dbg](https://user-images.githubusercontent.com/26707219/64764397-442f0200-d542-11e9-8705-e94bde6f516d.png)
![fischer_werkzeugmaschinen01_1900_OCR-D-IMG-CROP_0009](https://user-images.githubusercontent.com/26707219/64764398-442f0200-d542-11e9-89d5-0a4c5dfdf771.png)

**Comment by wrznr** [comment]
﻿The same issue on page 0011!
![fischer_werkzeugmaschinen01_1900_OCR-D-IMG-CROP_0011 dbg](https://user-images.githubusercontent.com/26707219/64764475-6de82900-d542-11e9-9944-e3c56b973558.png)
![fischer_werkzeugmaschinen01_1900_OCR-D-IMG-CROP_0011](https://user-images.githubusercontent.com/26707219/64764476-6de82900-d542-11e9-8e42-e20904460910.png)

**Comment by wrznr** [comment]
Also on pages 0012 and 0013.

**Comment by tboenig** [comment]
fixed
