### ISSUE TITLE
1000pages: Separator classified as text on page 0018 of "fontane_brandenburg04_1882""

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#47]
The separator on the left just before the poem is clearly not a text region.
![fontane_brandenburg04_1882_OCR-D-IMG-CROP_0018 dbg](https://user-images.githubusercontent.com/26707219/64764725-02eb2200-d543-11e9-94b7-d04d98d597e4.png)
![fontane_brandenburg04_1882_OCR-D-IMG-CROP_0018](https://user-images.githubusercontent.com/26707219/64764726-0383b880-d543-11e9-9a36-7b17d68d5580.png)

**Comment by wrznr** [comment]
It is also a problem that those separators are sometimes annotated and sometimes not in this volume.

**Comment by tboenig** [comment]
fixed
