### ISSUE TITLE
1000pages: Separators missing in "forster_reise02_1780"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#48]
They have been forgotten (not just on this page):
![forster_reise02_1780_OCR-D-IMG-CROP_0016 dbg](https://user-images.githubusercontent.com/26707219/64764945-79881f80-d543-11e9-9f84-d09e52d9c876.png)
![forster_reise02_1780_OCR-D-IMG-CROP_0016](https://user-images.githubusercontent.com/26707219/64764946-79881f80-d543-11e9-8651-5e30a06be91e.png)

**Comment by tboenig** [comment]
fixed
