### ISSUE TITLE
1000pages: Separator missing on title page of "gall_untersuchungen_1791"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#49]
Two separators have been annotated, one not:
![gall_untersuchungen_1791_OCR-D-IMG-CROP_0001 dbg](https://user-images.githubusercontent.com/26707219/64765163-f0bdb380-d543-11e9-9898-88445d586322.png)
![gall_untersuchungen_1791_OCR-D-IMG-CROP_0001](https://user-images.githubusercontent.com/26707219/64765165-f0bdb380-d543-11e9-8295-8bf4c228a362.png)

**Comment by tboenig** [comment]
fixed
