### ISSUE TITLE
1000pages: Separator missing on page 0013 of "hippel_lebenslaeufe0301_1781"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#53]
Three of them are annotated, one is not:
![hippel_lebenslaeufe0301_1781_OCR-D-IMG-CROP_0013 bin](https://user-images.githubusercontent.com/26707219/64767073-56f80580-d547-11e9-862c-3f35c3674c04.png)
![hippel_lebenslaeufe0301_1781_OCR-D-IMG-CROP_0013 dbg](https://user-images.githubusercontent.com/26707219/64767074-57909c00-d547-11e9-92dc-a99fe9174724.png)

**Comment by tboenig** [comment]
fixed

**Comment by wrznr** [comment]
Many thanks!
