### ISSUE TITLE
1000pages: Separators missing on page 0010 of "immermann_muenchhausen02_1839"

### ISSUE THREAD

**Issue by wrznr** [OCR-D/assets#57]
Some are there, some are not.
![immermann_muenchhausen02_1839_OCR-D-IMG-CROP_0010 bin](https://user-images.githubusercontent.com/26707219/64768438-b8b96f00-d549-11e9-8f49-5261d1ac15ad.png)
![immermann_muenchhausen02_1839_OCR-D-IMG-CROP_0010 dbg](https://user-images.githubusercontent.com/26707219/64768439-b9520580-d549-11e9-98f8-fcd50c546b63.png)

**Comment by tboenig** [comment]
corrected
