### ISSUE TITLE
Change the file name in DFKI test data 

### ISSUE THREAD

**Issue by n00blet** [OCR-D/assets#61]
Can you please change the file name according to mets file ?? 
The href in mets points to "**becker_quaestio_1586_00013.tif**" but the physical file name in OCR-D-IMG is different (tiff.tif). 
It should be a simple filename change, thank you.

**Comment by kba** [comment]
Can you send a PR? No notebook at the moment. Thank you!

**Comment by n00blet** [comment]
I have sent a PR.
