### ISSUE TITLE
Add references to OCR-D Ground Truth repo.

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/assets#65]
Assets of GT repo can now be referenced via their OCRD identifier.
e.g.: https://ocr-d-repo.scc.kit.edu/api/v1/metastore/bagit/ocrdidentifier?ocrdidentifier=ocrd_data_structur_wundt_grundriss_1896

**Comment by EEngl52** [comment]
can this issue be closed @VolkerHartmann ?
