### ISSUE TITLE
Repository not usable on case insensitive filesystems (like macOS and Windows)

### ISSUE THREAD

**Issue by stweil** [OCR-D/assets#68]
Case insensitive filesystems like those used on macOS and Windows by default have problems with these files:

	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-kim/OCR-D-SEG-PAGE-kim-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-niblack/OCR-D-SEG-PAGE-niblack-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-otsu/OCR-D-SEG-PAGE-otsu-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-sauvola-ms-fg/OCR-D-SEG-PAGE-sauvola-ms-fg-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-sauvola-ms-split/OCR-D-SEG-PAGE-sauvola-ms-split-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-sauvola-ms/OCR-D-SEG-PAGE-sauvola-ms-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-sauvola/OCR-D-SEG-PAGE-sauvola-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-singh/OCR-D-SEG-PAGE-singh-orig_tiff.xml
	modified:   data/scribo-test/data/OCR-D-SEG-PAGE-wolf/OCR-D-SEG-PAGE-wolf-orig_tiff.xml

This is caused by directory names like for example `OCR-D-SEG-PAGE-kim` and `OCR-D-SEG-PAGE-KIM` which only differ in case.

**Comment by stweil** [comment]
The `assets` repository is used by `ocrd_olena` which is used by `ocrd_all`, so that is affected.

`git status` for `ocrd_all` on macOS always shows modified content:

	modified:   ocrd_olena (modified content)

As the data seems to be related to tests, `ocrd_all` should be usable nevertheless.

**Comment by kba** [comment]
Windows sipport ist not a priority but Mac osx we should be able to support with to much effort.

**Comment by kba** [comment]
> Case insensitive filesystems

I had this one stew for a bit before it hit me: We have always one microphones around us that have been trained with a bazillion languages, Unicode turd color modifiers and Moby Dick translated to Emoji. But we still have file systems without support for lowercase letters.

**Comment by stweil** [comment]
... plus text editors which behave like an old typewriter and need a carriage return before going to the next line of text, and not to forget operating systems which expect the local time stored in the hardware clock. All those anachronisms already costed billions of dollars.

**Comment by kba** [comment]
`<rant>`Sometimes I wonder why not just quit all that new-fangled, scrummy, transparent, Free Software, agile, JIT-compiled, common language infrastructure nonsense, dust off my COBOL skills and make decent money keeping creaky fintech working for another 50 years instead of all this nonsense where it's easier to support some shity corporate idea of a gun 🔫 than a letigitimate ligature that has been around for 600 years.`</rant>`

**Comment by stweil** [comment]
This issue was fixed by commit 9f3808c5d1604e97060b06bafea72a649eb1a334.
